// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhRq_9y1q7qRc6neFBwAWYlZJPemd0Kbs',
    appId: '1:665833449810:web:dbaff748167ff0f640328b',
    messagingSenderId: '665833449810',
    projectId: 'whatsapp-backend-b48c0',
    authDomain: 'whatsapp-backend-b48c0.firebaseapp.com',
    storageBucket: 'whatsapp-backend-b48c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw0lC8U3TkhAV4e9L23s4b2x71AxSm78Y',
    appId: '1:665833449810:android:12b14a303acc53e540328b',
    messagingSenderId: '665833449810',
    projectId: 'whatsapp-backend-b48c0',
    storageBucket: 'whatsapp-backend-b48c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwxnwwPbZO9xPqsAkLIEd324mtj6x97Oo',
    appId: '1:665833449810:ios:2e358620f21ca27340328b',
    messagingSenderId: '665833449810',
    projectId: 'whatsapp-backend-b48c0',
    storageBucket: 'whatsapp-backend-b48c0.appspot.com',
    androidClientId: '665833449810-om7bu0h6gon56nllgs6djnfqnaqfso0l.apps.googleusercontent.com',
    iosClientId: '665833449810-ns7qo6qu6864a3mhij2eossi6h065mst.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappCloneRivaan',
  );
}
