// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnVPD6pA3wvU2-jL2oKn_8VKTM3eyTTAc',
    appId: '1:1032291382278:web:316246e1384ed5833b7f87',
    messagingSenderId: '1032291382278',
    projectId: 'flutterfcmpushnotificati-216a4',
    authDomain: 'flutterfcmpushnotificati-216a4.firebaseapp.com',
    storageBucket: 'flutterfcmpushnotificati-216a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNdwdxQhoDVDQbmdNCOG6rzXKO-8rcPKw',
    appId: '1:1032291382278:android:eab5e939c9134a323b7f87',
    messagingSenderId: '1032291382278',
    projectId: 'flutterfcmpushnotificati-216a4',
    storageBucket: 'flutterfcmpushnotificati-216a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU1BvEZ_Ju_qfaALv6Iixxnvb7EIlM1oY',
    appId: '1:1032291382278:ios:d13a0a926fcda83a3b7f87',
    messagingSenderId: '1032291382278',
    projectId: 'flutterfcmpushnotificati-216a4',
    storageBucket: 'flutterfcmpushnotificati-216a4.appspot.com',
    iosClientId: '1032291382278-16qcrl6h0r5140art9mhif6e4b1r63an.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );
}
